### ISSUE TITLE
Items for primitive 0.9.0.0

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#378]
We need to get 0.9.0.0 out to fix the type signature of `keepAlive`. Here are some other things I'd like to resolve:

- [x] Fix the type of `keepAlive`
- [x] Stop exporting fromArray and fromArrayN from Data.Primitive.Array, completed in https://github.com/haskell/primitive/pull/377 
- [x] Add `withByteArrayContents`, `withMutableByteArrayContents`, `withPrimArrayContents`, `withMutablePrimArrayContents` as helpers for the extremely common case of using `byteArrayContents` and `keepAlive#` together. Note that this cannot currently be implemented with our lifted `keepAlive` since it targets the wrapper types rather than the actual arrays.
- [x] Figure out whether or not to move over the `PrimUnlifted` class, tracked at https://github.com/haskell/primitive/issues/379
- [x] Size of small arrays, tracked at https://github.com/haskell/primitive/issues/373
- [x] Probably not going to take action on https://github.com/haskell/primitive/issues/356 for now.
- [x] Use `mutableByteArrayContents#` to avoid an `unsafeCoerce#` on newer GHCs, tracked at https://github.com/haskell/primitive/issues/376, still need to figure out which version of GHC first introduced this new primop.
- [x] Merge in https://github.com/haskell/primitive/pull/371
- [x] Merge in https://github.com/haskell/primitive/pull/183
- [x] Use GHC 9.6.1 in CI

**Comment by chessai** [comment]
> - [x] Stop exporting fromArray and fromArrayN from Data.Primitive.Array, completed in https://github.com/haskell/primitive/pull/377 

Did you mean fromList and fromListN?

> - [ ] Add `withByteArrayContents`, `withMutableByteArrayContents`, `withPrimArrayContents`, `withMutablePrimArrayContents` as helpers for the extremely common case of using `byteArrayContents` and `keepAlive#` together. Note that this cannot currently be implemented with our lifted `keepAlive` since it targets the wrapper types rather than the actual arrays.

+1

> - [ ] Figure out whether or not to move over the `PrimUnlifted` class, tracked at https://github.com/haskell/primitive/issues/379

+1

> - [ ] Size of small arrays, tracked at https://github.com/haskell/primitive/issues/373

Deprecate, +1

> - [ ] Probably not going to take action on https://github.com/haskell/primitive/issues/356 for now.

I think this should come in a later release

> - [ ] Use `mutableByteArrayContents#` to avoid an `unsafeCoerce#` on newer GHCs, tracked at https://github.com/haskell/primitive/issues/376, still need to figure out which version of GHC first introduced this new primop.

https://github.com/haskell/primitive/issues/376#issuecomment-1481324518

**Comment by chessai** [comment]
What about https://github.com/haskell/primitive/pull/371?

**Comment by chessai** [comment]
Also https://github.com/haskell/primitive/pull/183 is low-hanging fruit IMO.

**Comment by andrewthad** [comment]
There has been a ruling on the future of the `keepAlive#` primop. It will be made polymorphic in the state token in future versions of GHC, so we should `unsafeCoerce#` to give it that type for now, and then we can add CPP guards around it to remove it in future GHCs.

**Comment by andrewthad** [comment]
I'll be merging https://github.com/haskell/primitive/pull/395 soon, which will finish the list. If anyone's got anything else they'd like to see in 9.0, speak up now.

**Comment by andrewthad** [comment]
I have PR up for `withPrimArrayContents` and `withMutablePrimArrayContents`. I am planning on releasing after it is merged.

**Comment by andrewthad** [comment]
This list is now complete. I will release 0.9.0.0 this week.

**Comment by chessai** [comment]
> This list is now complete. I will release 0.9.0.0 this week.

Did we want to delay for any reason?

**Comment by andrewthad** [comment]
I have just now released primitive 0.9.0.0 to hackage. Closing.
